# Generated by Django 3.1.5 on 2021-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='score',
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
